### ISSUE TITLE
Deep Fry images

### ISSUE THREAD

**Issue by MaikoKingma** [Lerke/DankTimesBot-Plugin-Spongemock#1]
Feature idea:
When /spongemock is used as a reply or in the text of an image. Return the image deep fried.
Feature idea++:
When /spongemock is used in the text of an image. Return the image deep fried but also spongemock the text send with the image.

**Comment by MaikoKingma** [comment]
Things like /deepfry or /needsmorejpg could also be a separate plugin.

**Comment by Lerke** [comment]
Any thoughts about some sort of process or algorithm in order to deepfry jpegs?

**Comment by Lerke** [comment]
This now actually exists: https://github.com/Lerke/DankTimesBot-Plugin-DeepFry
