### ISSUE TITLE
Spongemock doesn't work on image captions

### ISSUE THREAD

**Issue by MaikoKingma** [Lerke/DankTimesBot-Plugin-Spongemock#10]
When a message contains an image with a caption I'd expect the spongemock functionality to still work on the message.

Actual:
![image](https://user-images.githubusercontent.com/21357422/178281571-58359da9-4cea-4bff-8f91-e1c37c6eec7e.png)

Expected dtb to respond with: I fRiEd YoUr PiCtUrE 10 tImEs!

**Comment by rbrants** [comment]
Fixed in #13
