### ISSUE TITLE
Delete the message requesting the spongemock

### ISSUE THREAD

**Issue by rick-mittendorff** [Lerke/DankTimesBot-Plugin-Spongemock#3]
Delete the message/comment that is requesting the spongemock. It gives the spongemock a more natural feel and it reduces unnecessary spam.

Should be possible: https://stackoverflow.com/questions/35269776/telegram-bot-how-to-delete-or-remove-a-message-or-media-from-a-channel-or-group/43965602#43965602

**Comment by MaikoKingma** [comment]
If the original message is deleted the bot should start the new message with the nickname of the original messages sender.

```
MyNickname:
mEsSaGeBoDy
```

**Comment by pommeldier** [comment]
I think that kinda ruins the purpose of spongemocking as it normally gets projected on the retard spongebob. The spongemock in DankTimesBot should probably feel the same way as the DankTimesBot is mocking your text.

**Comment by Lerke** [comment]
How about we delete the /spongemock message *and* have DankTimesBot reply to the original author with the spongemocked message?
